# Generated by Django 3.1.3 on 2020-11-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_system', '0002_auto_20201113_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sheetitem',
            name='pos',
            field=models.IntegerField(blank=True),
        ),
    ]
