# Generated by Django 3.1.3 on 2020-11-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_system', '0003_auto_20201113_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
